### ISSUE TITLE
Issue encountered while trying to install mitsuba python package

### ISSUE THREAD

**Issue by RuijiaX** [CMURoboTouch/mitsuba2-python-package#1]
I was trying to install the mitsuba package on windows for the first time using the command
`git clone git@github.com:CMURoboTouch/mitsuba2-python-package.git`

But I got an error message 
![;-;](https://user-images.githubusercontent.com/44103895/106195791-a8298900-617e-11eb-9d56-2ba6e3f00797.JPG)

**Comment by arpit15** [comment]
The problem is related to windows not allowing git to add itself to public keys. [This](https://docs.github.com/en/github/authenticating-to-github/error-permission-denied-publickey) might be helpful. Especially look at [this](https://docs.github.com/en/github/authenticating-to-github/error-permission-denied-publickey#make-sure-you-have-a-key-that-is-being-used) section

**Comment by arpit15** [comment]
Alternatively you can also use following command to get the repo
```
git clone https://github.com/CMURoboTouch/mitsuba2-python-package.git
```

**Comment by RuijiaX** [comment]
Thank you! I tried the alternative approach and it worked!
